# <img src="https://www.python.org/static/community_logos/python-logo-generic.svg" width="200"/> Data Science Mastery

## 🎓 The Complete Zero-to-Hero Guide

Welcome to the most comprehensive interactive guide for **Python** and **Data Science**. This notebook is essentially a textbook and a coding environment rolled into one.

### 🚀 Learning Roadmap
0.  **Absolute Basics**: Indentation, Comments, Inputs, and Math.
1.  **Python Fundamentals**: Variables, Control Flow, and Functions.
2.  **Advanced Python**: Exception Handling, Lambdas, and OOP.
3.  **File Operations**: Managing data sources (Text, JSON).
4.  **NumPy**: The engine of high-performance computing.
5.  **Pandas**: Data manipulation, cleaning, and Time Series analysis.
6.  **Visualization**: Bringing data to life with Matplotlib, Seaborn, WordClouds, and Folium Maps.

---

## 👶 Part 0: Absolute Basics
Before we write complex code, we must understand the "Grammar" of Python.

### 0.1 Comments
Code is for humans to read, not just machines. We use comments to explain our logic. The computer ignores these lines.

In [1]:
# This is a single-line comment. Python ignores this.
print("Hello World")  # You can also put comments at the end of a line

"""
This is a Multi-line comment (Docstring).
We use this for longer explanations.
It spans multiple lines.
"""
print("Comments are useful!")

Hello World
Comments are useful!


### 0.2 Indentation (The Golden Rule)
In many languages (C++, Java), you use `{ }` to group code. **In Python, we use Indentation (Spacing).**

If code is indented, it belongs to the block above it (like an `if` statement or a loop). Standard indentation is **4 Spaces** or **1 Tab**.

**Incorrect:**
```python
if True:
print("Error!") # No indentation
```

**Correct:**
```python
if True:
    print("Correct!") # Indented
```

In [5]:
# Try running this to see proper indentation in action
if 10 > 5:
    print("10 is greater than 5")
    print("This line is also inside the 'if' block")

print("This line is OUTSIDE the block (it runs no matter what)")

10 is greater than 5
This line is also inside the 'if' block
This line is OUTSIDE the block (it runs no matter what)


### 0.3 Input and Output
Interactive programs need to talk to the user.
*   `print()`: Shows information.
*   `input()`: Gets information.

**Important:** `input()` always returns a **String**. If you want a number, you must convert it!

In [9]:
# Basic Input
name = input("What is your name? ")
print("Welcome, " + name)

# Input with Type Conversion (Casting)
age_str = input("Enter your age: ")
age = int(age_str)  # Convert string "25" to integer 25

print(f"Next year you will be {age + 1}")

What is your name? I
Welcome, I
Enter your age: 25
Next year you will be 26


### 0.4 Mathematical Operators
Python is a powerful calculator.

| Operator | Name | Example | Result | Explanation |
| :---: | :--- | :--- | :--- | :--- |
| `+` | Addition | `10 + 5` | `15` | Adds values |
| `-` | Subtraction | `10 - 2` | `8` | Subtracts values |
| `*` | Multiplication | `4 * 3` | `12` | Multiplies values |
| `/` | Division | `10 / 2` | `5.0` | **Always returns a float** |
| `//` | Floor Division | `10 // 3` | `3` | Removes decimal part (rounds down) |
| `%` | Modulus | `10 % 3` | `1` | Remainder of division (10 = 3*3 + **1**) |
| `**` | Exponent | `2 ** 3` | `8` | 2 to the power of 3 (2*2*2) |

In [10]:
x = 10
y = 3

print(f"Division (10 / 3):       {x / y}")
print(f"Floor Division (10 // 3): {x // y}")
print(f"Modulus (10 % 3):        {x % y}")
print(f"Power (10 ** 3):         {x ** y}")

Division (10 / 3):       3.3333333333333335
Floor Division (10 // 3): 3
Modulus (10 % 3):        1
Power (10 ** 3):         1000


---

## 🧩 Part 1: Python Core Fundamentals

### 1.1 Variables & Data Principles
Python is a **dynamically typed** language, meaning you don't need to declare the type of a variable explicitly. The interpreter infers it at runtime.

**Core Data Types:**
*   `int`: Whole numbers (e.g., 10, -5).
*   `float`: Decimal numbers (e.g., 3.14, 2.0).
*   `str`: Text data (e.g., "Hello").
*   `bool`: Logical values (`True` or `False`).

In [11]:
# Variable Assignment
xp_points = 1500           # Integer
accuracy_rate = 0.985      # Float
user_name = "DataWizard123"   # String
is_admin = True            # Boolean

# Printing with Type Inspection
print(f"User: {user_name} (Type: {type(user_name)})")
print(f"XP: {xp_points} (Type: {type(xp_points)})")
print(f"Admin Access: {is_admin} (Type: {type(is_admin)})")

User: DataWizard123 (Type: <class 'str'>)
XP: 1500 (Type: <class 'int'>)
Admin Access: True (Type: <class 'bool'>)


### 1.2 Data Structures (The Containers)
Data structures organize and store data. Choosing the right one is critical for performance.

| Structure | Syntax | Mutable? | Ordered? | Duplicates? | Description |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **List** | `[1, 2]` | ✅ Yes | ✅ Yes | ✅ Yes | General purpose array. |
| **Tuple** | `(1, 2)` | ❌ No | ✅ Yes | ✅ Yes | Immutable collection. Faster than lists. |
| **Set** | `{1, 2}` | ✅ Yes | ❌ No | ❌ No | Unique elements only. Fast lookups. |
| **Dict** | `{'k': 'v'}` | ✅ Yes | ✅ Yes | ❌ Keys | Key-Value mappings. The most powerful structure. |

In [12]:
# --- LISTS (Mutable sequences) ---
skills = ["Python", "SQL", "Tableau"]
skills.append("Machine Learning")  # Adding an item
print(f"Skills List: {skills}")
print(f"First Skill: {skills[0]}")

# --- TUPLES (Read-only sequences) ---
db_config = ("192.168.1.5", 5432)  # (grapht, port)
# db_config[0] = "localhost"  # This would causing an ERROR
print(f"Database Port: {db_config[1]}")

# --- SETS (Unique items) ---
tags = {"AI", "ML", "AI", "Data", "ML"}
print(f"Unique Tags: {tags}")  # Duplicates automatically removed

# --- DICTIONARIES (Key-Value) ---
model_metrics = {
    "accuracy": 0.89,
    "f1_score": 0.87,
    "recall": 0.92
}
print(f"Model Accuracy: {model_metrics['accuracy']}")

Skills List: ['Python', 'SQL', 'Tableau', 'Machine Learning']
First Skill: Python
Database Port: 5432
Unique Tags: {'Data', 'ML', 'AI'}
Model Accuracy: 0.89


### 1.3 Control Flow logic
Programming is about making decisions (`if-else`) and repeating tasks (`loops`).

#### 🌟 The Star Pattern Exercise
A classic logic building exercise. We use nested loops to print patterns.

In [13]:
print("--- Standard Loop ---")
rows = 5
for i in range(1, rows + 1):
    # Inner loop isn't needed here if we use string multiplication
    # '*' * 3 results in '***'
    print("*" * i)

print("\n--- List Comprehension (Advanced) ---")
# Creating a list of squares for even numbers only
numbers = range(10)
print(list(numbers))
even_squares = [n**2 for n in numbers if n % 2 == 0]
print(f"Even Squares: {even_squares}")

--- Standard Loop ---
*
**
***
****
*****

--- List Comprehension (Advanced) ---
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Even Squares: [0, 4, 16, 36, 64]


## ⚙️ Part 2: Advanced Python Concepts

### 2.1 Exception Handling
Code crashes. Good developers handle crashes gracefully. We use `try`, `except`, and `finally` blocks.

*   **Try**: Run this code.
*   **Except**: If an error happens, run this.
*   **Finally**: Always run this (good for cleanup).

In [14]:
def safe_division(a, b):
    try:
        result = a / b
        return result
    except ZeroDivisionError:
        return "Error: Cannot divide by zero!"
    except TypeError:
        return "Error: Inputs must be numbers!"
    finally:
        print("Execution attempt finished.")

print(safe_division(10, 2))
print(safe_division(10, 0))
print(safe_division(10, "two"))

Execution attempt finished.
5.0
Execution attempt finished.
Error: Cannot divide by zero!
Execution attempt finished.
Error: Inputs must be numbers!


### 2.2 Functional Programming: Lambda, Map, Filter
*   **Lambda**: Anonymous, one-line functions.
*   **Map**: Apply a function to every item in a list.
*   **Filter**: Keep only items that satisfy a condition.

In [16]:
nums = [1, 2, 3, 4, 5]

# Square every number using Map + Lambda
squared = list(map(lambda x: x**2, nums))
print(f"Squared: {squared}")
# Keep only numbers > 2 using Filter + Lambda
big_nums = list(filter(lambda x: x > 2, nums))
print(f"Numbers > 2: {big_nums}")

Squared: [1, 4, 9, 16, 25]
Numbers > 2: [3, 4, 5]


## 📂 Part 3: File I/O Management

Handling external data is crucial. Python allows reading and writing in various modes.

| Mode | Description |
| :--- | :--- |
| `'r'` | **Read** (Default). Error if file doesn't exist. |
| `'w'` | **Write**. Overwrites entire file. Creates if not exists. |
| `'a'` | **Append**. Adds to end of file. |
| `'r+'`| Read and Write. |

In [17]:
import os
import json

# 1. Writing a Text File
with open("logs.txt", "w") as f:
    f.write("System Start: 10:00 AM\n")
    f.write("User Login: Admin\n")

# 2. Appending to a Text File
with open("logs.txt", "a") as f:
    f.write("Action: Update Database\n")

print("--- Reading Log File ---")
with open("logs.txt", "r") as f:
    print(f.read())

# 3. Handling JSON Data
config = {
    "theme": "dark",
    "notifications": True,
    "max_retries": 5
}

with open("config.json", "w") as f:
    json.dump(config, f, indent=4)

print("\n--- Loaded JSON Config ---")
with open("config.json", "r") as f:
    loaded = json.load(f)
    print(loaded)

--- Reading Log File ---
System Start: 10:00 AM
User Login: Admin
Action: Update Database


--- Loaded JSON Config ---
{'theme': 'dark', 'notifications': True, 'max_retries': 5}


## 🔢 Part 4: NumPy (Numerical Python)

<img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" width="200"/>

NumPy is the foundation of scientific computing. It replaces Python's slow lists with fast **Arrays**.

In [ ]:
import numpy as np

# Creating Arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized Operations (So much faster than loops!)
print(f"Addition: {a + b}")
print(f"Multiplication: {a * b}")

# Matrix Operations
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.eye(2) # Identity matrix

print(f"\nDot Product:\n{np.dot(matrix_a, matrix_b)}")

# Reshaping
grid = np.arange(9).reshape(3, 3)
print(f"\n3x3 Grid:\n{grid}")

Addition: [5 7 9]
Multiplication: [ 4 10 18]

Dot Product:
[[1. 2.]
 [3. 4.]]

3x3 Grid:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 🐼 Part 5: Pandas (Data Analysis)

<img src="https://upload.wikimedia.org/wikipedia/commons/e/ed/Pandas_logo.svg" width="200"/>

Pandas is the 'Excel' of Python. We work with **DataFrames**.

### 5.1 Creating and Merging Data

In [ ]:
import pandas as pd

# Dataset A: Employees
df_emp = pd.DataFrame({
    'ID': [101, 102, 103],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Dept_ID': ['D1', 'D2', 'D1']
})
print(df_emp)
# Dataset B: Departments
df_dept = pd.DataFrame({
    'Dept_ID': ['D1', 'D2', 'D3'],
    'Dept_Name': ['HR', 'Tech', 'Finance']
})
print(df_dept)
# Merging (SQL Join)
merged = pd.merge(df_emp, df_dept, on='Dept_ID', how='left')
print("--- Merged DataFrame ---")
print(merged)

### 5.2 Time Series Analysis
Pandas is incredibly strong at handling time-stamped data.

In [ ]:
# Generate date range
dates = pd.date_range(start='2023-01-01', periods=6, freq='D')
df_time = pd.DataFrame({
    'Date': dates,
    'Sales': [100, 120, 90, 110, 130, 150]
})

# Set Date as Index
df_time.set_index('Date', inplace=True)

# Resampling (e.g., Calculate 2-Day sum)
resampled = df_time.resample('2D').sum()
print("--- Resampled (2-Day Sum) ---")
print(resampled)

## 📊 Part 6: Advanced Visualization

### 6.1 Matplotlib & Seaborn
Standard plotting libraries.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Installation of extra libraries just in case
!pip install wordcloud folium

# Setup
sns.set_theme(style="darkgrid")

# Bar Plot
plt.figure(figsize=(6, 4))
sns.barplot(x='Name', y='Sales', data=df_time.reset_index().rename(columns={'Date': 'Name'}), palette='magma')
plt.title("Sales over Time")
plt.show()

### 6.2 Word Clouds
Visualizing text frequency (Great for NLP).

In [ ]:
from wordcloud import WordCloud

text_data = "Python is amazing. Python is fast. Data Science requires Python. Machine Learning uses Python."

wc = WordCloud(width=800, height=400, background_color='black', colormap='rainbow').generate(text_data)

plt.figure(figsize=(10, 5))
plt.imshow(wc, interpolation='bilinear')
plt.axis("off")
plt.title("Word Frequency Cloud")
plt.show()

### 6.3 Geospatial Maps (Folium)
Interactive coding maps.

In [ ]:
import folium

# Center View on India
m = folium.Map(location=[20.5937, 78.9629], zoom_start=5, tiles="OpenStreetMap")

# Add Markers
locations = [
    {"loc": [28.6139, 77.2090], "name": "New Delhi", "info": "Capital"},
    {"loc": [19.0760, 72.8777], "name": "Mumbai", "info": "Finance Hub"},
    {"loc": [12.9716, 77.5946], "name": "Bangalore", "info": "Tech Hub"}
]

for place in locations:
    folium.Marker(
        location=place["loc"],
        popup=f"<b>{place['name']}</b><br>{place['info']}",
        icon=folium.Icon(color="blue", icon="info-sign")
    ).add_to(m)

m